#!/usr/bin/env python3
"""Derive the SQLite variant of ctl_framework.sql.

Some engine instances run on the engine's native SQLite instead of a per-tenant
Postgres database. The catalog is reference data and has to exist in both, so
this translation is generated rather than maintained by hand — edit
ctl_framework.sql and re-run.
"""
import re
s = open('ctl_framework.sql').read()
s = s.replace('SERIAL PRIMARY KEY', 'INTEGER PRIMARY KEY AUTOINCREMENT')
s = s.replace('JSONB', 'TEXT')
s = re.sub(r"::text\b", "", s, flags=re.I)
s = re.sub(r"::jsonb\b", "", s, flags=re.I)

# --- SQLite has no LATERAL. The subquery only names one boolean, so inline it. ---
OK = """(tpl.template IS NOT NULL AND (c.gate IS NULL OR (c.gate='chamber' AND pt.has_chamber_heater) OR (c.gate='aux_fan' AND pt.has_aux_fan) OR (c.gate='chamber_fan' AND pt.has_chamber_heater) OR (c.gate='multi_nozzle' AND pt.nozzle_count>=2) OR (c.gate='bambu_only' AND pt.mechanism_key='bambu_mqtt')))"""
i = s.index('-- cross-reference: every printer_type x every command')
head, tail = s[:i], s[i:]
tail = tail[:tail.index('COMMIT;')]
tail = """-- cross-reference: every printer_type x every command, resolved to supported/UNSUPPORTED
INSERT INTO ctl_printer_command_support (printer_type_id, command_key, status, supported, reason)
SELECT pt.id, c.key,
  CASE WHEN """ + OK + """ THEN 'supported' ELSE 'UNSUPPORTED' END,
  CASE WHEN """ + OK + """ THEN 1 ELSE 0 END,
  CASE
    WHEN """ + OK + """ THEN NULL
    WHEN c.gate='chamber'      AND NOT pt.has_chamber_heater THEN 'no chamber heater'
    WHEN c.gate='aux_fan'      AND NOT pt.has_aux_fan         THEN 'no auxiliary fan'
    WHEN c.gate='chamber_fan'  AND NOT pt.has_chamber_heater  THEN 'no chamber/exhaust fan'
    WHEN c.gate='multi_nozzle' AND pt.nozzle_count<2          THEN 'single nozzle'
    WHEN c.gate='bambu_only'   AND pt.mechanism_key<>'bambu_mqtt' THEN 'Bambu-only command'
    WHEN tpl.template IS NULL THEN 'no command mapping for '||pt.dialect_key||' dialect'
    ELSE 'unsupported'
  END
FROM ctl_printer_type pt
CROSS JOIN ctl_command c
LEFT JOIN ctl_command_template tpl ON tpl.dialect_key=pt.dialect_key AND tpl.command_key=c.key;

"""
s = head + tail + 'COMMIT;\n'

s = s.replace("BEGIN;", "-- Generated by gen_sqlite.py. Do not edit by hand.\nPRAGMA foreign_keys=ON;\nBEGIN;", 1)
open('ctl_framework.sqlite.sql','w').write(s)
print('wrote ctl_framework.sqlite.sql')
